### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by peterdtitan** [IamYunusAli/portfolio#5]
Please use proper commits to help track your work and give an idea of changes that have been made to a repo.
You can refer to the Microverse Curriculum Skills "Documenting Repo inf a Professional Manner" for a refresher guide.

**Comment by Nedramrez** [comment]
I think that it's better to use semantic tags. For example, you can wrap your "Contact me" field in the footer tag. Additional information can be found [here](https://www.microverse.org/blog/3-important-frontend-concepts-that-make-you-a-professional).
